version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/uploads:/app/uploads
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    entrypoint: []
